name: build

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Debug, Release]
    
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Install gcc-10
      if: contains(${{ matrix.os }}, "ubuntu")
      run: sudo apt-get install -y gcc-10 g++-10

    - name: Generate
      shell: bash
      run: bash scripts/gen -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
      
    - name: Build
      shell: bash
      run: bash scripts/build

    - name: Test
      shell: bash
      run: bash scripts/test
