name: ubuntu

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build_type: ['Debug', 'Release']
    
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Install gcc-10
      run: sudo apt-get install -y gcc-10 g++-10

    - name: Generate
      shell: bash
      run: scripts/gen -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DCMAKE_C_COMPILER=gcc-10 -DCMAKE_CXX_COMPILER=g++-10
      
    - name: Build
      shell: bash
      run: scripts/build

    - name: Test
      shell: bash
      run: scripts/test
